name: Deploy (staging)
"on": workflow_dispatch
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}
      APP_ENV: staging
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: pnpm install
      - run: pnpm build
      - run: pnpm firebase deploy --project $APP_ENV
